create database university;
use university;
create table student(name varchar(30),student_number int primary key,class int,major varchar(5));
insert into student values('smith',17,1,'CS');
insert into student values('brown',8,2,'CS');
create table course(course_name varchar(50),course_number varchar(20) primary key, credit_hours int,department varchar(5));
insert into course values('into to computer science','CS1310',4,'CS');
insert into course values('Data structures','CS3320',4,'CS');
insert into course values('Descrete mathematics','MATH2410',3,'MATH');
insert into course values('Database','CS3380',3,'CS');
create table section(section_identifier int primary key,course_number varchar(20),semester varchar(20),year int,instructor varchar(20),foreign key(course_number) references course(course_number));
insert into section values(85,'MATH2410','fall',07,'king');
insert into section values(92,'CS1310','fall',07,'anderson');
insert into section values(102,'CS3320','spring',08,'knuth');
insert into section values(112,'MATH2410','fall',08,'chang');
insert into section values(119,'CS1310','fall',08,'anderson');
insert into section values(135,'CS3380','fall',08,'stone');
create table grade_report(student_number int,section_identifier int,grade varchar(5),foreign key(student_number) references student(student_number),foreign key(section_identifier) references section(section_identifier));
insert into grade_report values(17,112,'B');
insert into grade_report values(17,119,'C');
insert into grade_report values(8,85,'A');
insert into grade_report values(8,92,'A');
insert into grade_report values(8,102,'B');
insert into grade_report values(8,135,'A');
create table prerequisite(course_number varchar(20),prerequisite_number varchar(20),foreign key(course_number) references course(course_number),foreign key(prerequisite_number)references course(course_number));
insert into prerequisite values('CS3380','CS3320');
insert into prerequisite values('CS3380','MATh2410');
insert into prerequisite values('CS3320','CS1310');
select course_name from course;
use university;
select course.course_name,grade_report.grade from course join (section join grade_report on section.section_identifier=grade_report.section_identifier) on course.course_number=section.course_number where grade_report.student_number=(select student_number from student where name='smith');
select student.name,grade_report.grade from student join (grade_report join (section join course on course.course_number=section.course_number) on section.section_identifier=grade_report.section_identifier)on student.student_number=grade_report.student_number where section.semester='fall' and section.year=8 and course.course_name='database';
select c.course_name from course join (prerequisite join  course  as c on prerequisite.prerequisite_number=c.course_number)on prerequisite.course_number=course.course_number where course.course_number=(select course_number from course where course_name='database');
select name from student where major='CS';
select course.course_name from course join section on course.course_number=section.course_number where section.instructor='king' and (section.year=7 or section.year=8);
select section.course_number,section.semester,section.year from section join (grade_report join student on grade_report.student_number=student.student_number) on section.section_identifier=grade_report.section_identifier where section.instructor='king';
select student.name,course.course_name,course.course_number,course.credit_hours,section.semester,section.year,grade_report.grade from student join (grade_report join (section join course on course.course_number=section.course_number) on section.section_identifier=grade_report.section_identifier)on student.student_number=grade_report.student_number;
use university;
insert into student values('Johnson',25,1,'MATH');
update student set class=2 where name='smith';
insert into course values('Knowledge engineering','CS4390',3,'CS');
