create database university;
use university;
create table student(name varchar(30),student_number int primary key,class int,major varchar(5));
insert into student values('smith',17,1,'CS');
insert into student values('brown',8,2,'CS');
create table course(course_name varchar(50),course_number varchar(20) primary key, credit_hours int,department varchar(5));
insert into course values('into to computer science','CS1310',4,'CS');
insert into course values('Data structures','CS3320',4,'CS');
insert into course values('Descrete mathematics','MATH2410',3,'MATH');
insert into course values('Database','CS3380',3,'CS');
create table section(section_identifier int primary key,course_number varchar(20),semester varchar(20),year int,instructor varchar(20),foreign key(course_number) references course(course_number));
insert into section values(85,'MATH2410','fall',07,'king');
insert into section values(92,'CS1310','fall',07,'anderson');
insert into section values(102,'CS3320','spring',08,'knuth');
insert into section values(112,'MATH2410','fall',08,'chang');
insert into section values(119,'CS1310','fall',08,'anderson');
insert into section values(135,'CS3380','fall',08,'stone');
create table grade_report(student_number int,section_identifier int,grade varchar(5),foreign key(student_number) references student(student_number),foreign key(section_identifier) references section(section_identifier));
insert into grade_report values(17,112,'B');
insert into grade_report values(17,119,'C');
insert into grade_report values(8,85,'A');
insert into grade_report values(8,92,'A');
insert into grade_report values(8,102,'B');
insert into grade_report values(8,135,'A');
create table prerequisite(course_number varchar(20),prerequisite_number varchar(20),foreign key(course_number) references course(course_number),foreign key(prerequisite_number)references course(course_number));
insert into prerequisite values('CS3380','CS3320');
insert into prerequisite values('CS3380','MATh2410');
insert into prerequisite values('CS3320','CS1310');
select course_name from course;
